name: 'Get Dependencies'
description: 'Get Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Restore Cache
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ github.run_id }}-node-modules
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
