# .github/actions/cached-deps/action.yml
name: 'Get Dependencies'
description: 'Get Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0
    - name: Restore Cache
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ github.run_id }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ github.run_id }}-node-
          ${{ github.run_id }}-

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
