name: 'Get Dependencies'
description: 'Get Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Restore Cache
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm install
      shell: bash
