export enum WebRole {
  USER = 100,
  CHILD = 100,
  GURDIAN = 100,
  LEADER = 300,
  WORKER = 200,
  NURSERY_DIRECTOR = 300,
  NURSERY_WORKER = 200,
  JUNIOR_CHURCH_DIRECTOR = 300,
  JUNIOR_CHURCH_WORKER = 200,
  VBS_DIRECTOR = 300,
  VBS_WORKER = 200,
  VBS_REGISTRATION = 200,
  VBS_PRE_PRIMARY = 200,
  VBS_PRIMARY = 200,
  VBS_MIDDLER = 200,
  VBS_JUNIOR = 200,
  VBS_GAMES = 200,
  VBS_SNACKS = 200,
  VBS_CRAFTS = 200,
  AWANA_DIRECTOR = 400,
  AWANA_LEADER = 300,
  AWANA_WORKER = 200,
  TNT_LEADER = 300,
  TNT_WORKER = 200,
  SPARKS_LEADER = 300,
  SPARKS_WORKER = 200,
  CUBBIES_LEADER = 300,
  CUBBIES_WORKER = 200,
  CROSS_CHECK_LEADER = 300,
  CROSS_CHECK_WORKER = 200,
  SITE_ADMINISTRATOR = 500,
  ADMINISTRATOR = 1000,
}

export enum ChurchGroup {
  CUBBIES = 'CUBBIES',
  SPARKS = 'SPARKS',
  TNT_GIRLS = 'TNT_GIRLS',
  TNT_BOYS = 'TNT_BOYS',
  CROSS_CHECK = 'CROSS_CHECK',
  JUNIOR_CHURCH = 'JUNIOR_CHURCH',
  NURSERY = 'NURSERY',
  VBS_PRE_PRIMARY = 'VBS_PRE_PRIMARY',
  VBS_PRIMARY = 'VBS_PRIMARY',
  VBS_MIDDLER = 'VBS_MIDDLER',
  VBS_JUNIOR = 'VBS_JUNIOR',
}

export enum Relationship {
  MOTHER = 'MOTHER',
  FATHER = 'FATHER',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
  GRANDMA = 'GRANDMA',
  GRANDPA = 'GRANDPA',
  AUNT = 'AUNT',
  UNCLE = 'UNCLE',
  OTHER = 'OTHER',
}

export enum Access {
  CREATE = 'c',
  READ = 'r',
  UPDATE = 'u',
  DELETE = 'd',
}

export enum Feature {
  OVERVIEW = 'overview',
  DETAIL = 'detail',
  PROFILE = 'profile',
  NOTIFICATION = 'notification',
}

export enum App {
  USERS = 'users',
  CHILDREN = 'children',
  GURDIANS = 'gurdians',
  REPORTS = 'reports',
  ABOUT = 'about',
  REPOSITORIES = 'repositories',
  SETTINGS = 'settings',
  GLOBAL = 'global',
}
