# Build UI application.

name: FBL Church UI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install & Cache Node Modules
        uses: ./.github/actions/cached-node-modules

  validate:
    name: Validate
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Format Check
        run: npm run pipeline:format

  lint:
    name: Lint
    needs: install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Lint
        run: npm run pipeline:lint

  test:
    name: Test
    needs: install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Test
        run: npm run pipeline:test

  build:
    name: Build
    needs: [validate, lint, test]
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Build
        run: npm run build:production --if-present
