# Build UI application.

name: FBL Church UI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: FBL Church UI Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Install
        run: npm install
      - name: Format
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:headless
      - name: Build
        run: npm run build:production --if-present
