# Build UI application.

name: FBL Church UI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Install & Cache Node Modules
        uses: ./.github/actions/cached-node-modules

  lint:
    name: Lint
    needs: install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Lint
        run: npm run lint

  test:
    name: Test
    needs: install
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Test
        run: npm run test:headless

  build:
    name: Build
    needs: [lint, test]
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Build
        run: npm run build:production --if-present

  clean:
    name: Clean Up
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: |
          gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/fbl-church/fbl-church-app/actions/caches?key=$CACHE_KEY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CACHE_KEY: ${{ github.run_id }}-node-${{ hashFiles('**/package-lock.json') }}
