# Build UI application.

name: FBL Church UI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: windows-latest
    steps:
      - name: Install & Cache Node Modules
        uses: ./.github/actions/cached-node-modules

  validate:
    name: Validate
    needs: install
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Format Check
        run: npm run pipeline:format

  lint:
    name: Lint
    needs: install
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Lint
        run: npm run pipeline:lint

  test:
    name: Test
    needs: install
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Test
        run: npm run pipeline:test

  build:
    name: Build
    needs: [validate, lint, test]
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: ./.github/actions/cached-node-modules
      - name: Build
        run: npm run build:production --if-present

  clean:
    name: Clean Up
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: gh cache delete $CACHE_KEY --repo fbl-church/fbl-church-app
        env:
          GH_TOKEN: ${{ secrets.ACTION_CLEAR_CACHES_TOKEN  }}
          CACHE_KEY: ${{ github.run_id }}-node-modules
