# Build UI application.

name: FBL Church UI Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  install:
    name: Install
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Install
        run: npm install
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  lint:
    name: Lint
    needs: install
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Lint
        run: npm run lint

  test:
    name: Test
    needs: install
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Test
        run: npm run test:headless

  build:
    name: Build
    needs: test
    runs-on: windows-latest
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Build
        run: npm run build:production --if-present

  clean:
    name: Clean Up
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: |
          gh api \
          --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/fbl-church/fbl-church-app/actions/caches?key=$CACHE_KEY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CACHE_KEY: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
